server {
    listen 80;
    root /usr/share/nginx/html;

    location /api/ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /app/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param DOCUMENT_ROOT /app/public;
        fastcgi_pass api:9000;
        fastcgi_read_timeout 120s;
    }

    location /ws {
        proxy_pass http://ws:8081;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 1h;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
