services:
  api:
    command: php -S 0.0.0.0:8000 -t public
    environment:
      APP_ENV: dev
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"

  ws:
    environment:
      APP_ENV: dev
    volumes:
      - ./backend:/app
    ports:
      - "8081:8081"
