<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260930114105 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {

        $this->addSql('CREATE TABLE reaction (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nickname VARCHAR(50) NOT NULL, emoji VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, message_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_reaction ON reaction (message_id, nickname, emoji)');
        $this->addSql('CREATE INDEX IDX_A4D707F7537A1329 ON reaction (message_id)');
        $this->addSql('ALTER TABLE reaction ADD CONSTRAINT FK_A4D707F7537A1329 FOREIGN KEY (message_id) REFERENCES message (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {

        $this->addSql('ALTER TABLE reaction DROP CONSTRAINT FK_A4D707F7537A1329');
        $this->addSql('DROP TABLE reaction');
    }
}
