<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260930144017 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Таблица команд бота и команды по умолчанию';
    }

    public function up(Schema $schema): void
    {

        $this->addSql('CREATE TABLE bot_command (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(50) NOT NULL, description VARCHAR(255) NOT NULL, prompt TEXT NOT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_713C87F15E237E06 ON bot_command (name)');

        $commands = [
            [
                'перевод',
                'Перевести текст на русский язык',
                "Переведи на русский язык. В ответе напиши только перевод, без пояснений.\n\n{text}",
            ],
            [
                'english',
                'Перевести текст на английский язык',
                "Translate the text into English. Reply with the translation only.\n\n{text}",
            ],
            [
                'кратко',
                'Пересказать текст в одном-двух предложениях',
                "Перескажи кратко, в одном-двух предложениях:\n\n{text}",
            ],
            [
                'объясни',
                'Объяснить простыми словами',
                'Объясни простыми словами, как школьнику, не больше пяти предложений: {text}',
            ],
            [
                'исправь',
                'Исправить ошибки в тексте',
                "Исправь орфографические и пунктуационные ошибки в тексте. Верни только исправленный текст.\n\n{text}",
            ],
            [
                'шутка',
                'Придумать шутку на заданную тему',
                'Придумай одну короткую смешную шутку на тему: {text}',
            ],
        ];

        foreach ($commands as $command) {
            $this->addSql(
                'INSERT INTO bot_command (name, description, prompt, enabled) VALUES (?, ?, ?, true)',
                $command
            );
        }
    }

    public function down(Schema $schema): void
    {

        $this->addSql('DROP TABLE bot_command');
    }
}
